-- Formatos DateTime
DECLARE @Fecha DATETIME = GETDATE();

SELECT
	CONVERT(VARCHAR, @Fecha, 0) AS [Formato 0],
	CONVERT(VARCHAR, @Fecha, 1) AS [Formato 1],
	CONVERT(VARCHAR, @Fecha, 2) AS [Formato 2],
	CONVERT(VARCHAR, @Fecha, 3) AS [Formato 3],
	CONVERT(VARCHAR, @Fecha, 4) AS [Formato 4],
	CONVERT(VARCHAR, @Fecha, 5) AS [Formato 5],
	CONVERT(VARCHAR, @Fecha, 6) AS [Formato 6],
	CONVERT(VARCHAR, @Fecha, 7) AS [Formato 7],
	CONVERT(VARCHAR, @Fecha, 8) AS [Formato 8],
	CONVERT(VARCHAR, @Fecha, 9) AS [Formato 9],
	CONVERT(VARCHAR, @Fecha, 10) AS [Formato 10],
	CONVERT(VARCHAR, @Fecha, 11) AS [Formato 11],
	CONVERT(VARCHAR, @Fecha, 12) AS [Formato 12],
	CONVERT(VARCHAR, @Fecha, 13) AS [Formato 13],
	CONVERT(VARCHAR, @Fecha, 14) AS [Formato 14],
	CONVERT(VARCHAR, @Fecha, 20) AS [Formato 20],
	CONVERT(VARCHAR, @Fecha, 21) AS [Formato 21],
	CONVERT(VARCHAR, @Fecha, 22) AS [Formato 22],
	CONVERT(VARCHAR, @Fecha, 23) AS [Formato 23],
	CONVERT(VARCHAR, @Fecha, 24) AS [Formato 24],
	CONVERT(VARCHAR, @Fecha, 25) AS [Formato 25],
	CONVERT(VARCHAR, @Fecha, 100) AS [Formato 100],
	CONVERT(VARCHAR, @Fecha, 101) AS [Formato 101],
	CONVERT(VARCHAR, @Fecha, 102) AS [Formato 102],
	CONVERT(VARCHAR, @Fecha, 103) AS [Formato 103],
	CONVERT(VARCHAR, @Fecha, 104) AS [Formato 104],
	CONVERT(VARCHAR, @Fecha, 105) AS [Formato 105],
	CONVERT(VARCHAR, @Fecha, 106) AS [Formato 106],
	CONVERT(VARCHAR, @Fecha, 107) AS [Formato 107],
	CONVERT(VARCHAR, @Fecha, 108) AS [Formato 108],
	CONVERT(VARCHAR, @Fecha, 109) AS [Formato 109],
	CONVERT(VARCHAR, @Fecha, 110) AS [Formato 110],
	CONVERT(VARCHAR, @Fecha, 111) AS [Formato 111],
	CONVERT(VARCHAR, @Fecha, 112) AS [Formato 112],
	CONVERT(VARCHAR, @Fecha, 113) AS [Formato 113],
	CONVERT(VARCHAR, @Fecha, 114) AS [Formato 114],
	CONVERT(VARCHAR, @Fecha, 120) AS [Formato 120],
	CONVERT(VARCHAR, @Fecha, 121) AS [Formato 121],
	CONVERT(VARCHAR, @Fecha, 126) AS [Formato 126],
	CONVERT(VARCHAR, @Fecha, 127) AS [Formato 127],
	CONVERT(VARCHAR, @Fecha, 130) AS [Formato 130],
	CONVERT(VARCHAR, @Fecha, 131) AS [Formato 130];

-- Alternativa
SELECT FORMAT(GETDATE(), 'yyyyMMdd') AS [Alternativa a Formato 112];